name: flutter_movies_app
description: A Flutter movie browsing application connected to TMDB API.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  cached_network_image: ^3.4.1
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  logging: ^1.0.1
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/icons/app_icon.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/app_icon.png"
